FROM debian:sid-slim
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils ca-certificates && \
    apt-get install -y --no-install-recommends build-essential make git && \
    apt-get install -y --no-install-recommends cmake && \
    apt-get install -y --no-install-recommends libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir -p /project/cmake-build
WORKDIR /project/cmake-build